# kubectl apply -f app-user.yaml
# clear & kubectl get deployment & kubectl get service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-user
  template:
    metadata:
      labels:
        app: app-user
    spec:
      containers:
        - name: container-app-user
          image: thezion/k8s-app-user
          imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: app-user-nodeport
spec:
  type: NodePort
  selector:
    app: app-user
  ports:
    - name: app-user-ports
      protocol: TCP
      port: 5001
      targetPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: app-user-clusterip
spec:
  type: ClusterIP
  selector:
    app: app-user
  ports:
    - name: app-user-ports
      protocol: TCP
      port: 5001
      targetPort: 5001
